version: '3.8'

services:

  db:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: auto
    volumes:
      - ./db-data/mongo/:/data/db

  auto_parser:
    image: parser
    container_name: auto_parser
    command: python ./src/parser/parser.py
    depends_on:
      - db
    network_mode: host

  data_analyser:
    image: data-analytics
    command: python ./src/data-analytics/data_analytics.py
    depends_on:
      - db
    network_mode: host